services:
  niyyah2:
    image: ghcr.io/ferilee/api-niyyah2:latest
    container_name: niyyah2
    restart: unless-stopped
    ports:
      - "3001:3000" # Mapping port luar 3001 ke port dalam container 3000
    env_file:
      - .env
    networks:
      - ferileeNet

networks:
  ferileeNet:
    external: true
