services:
  api-niyyah2:
    image: ghcr.io/ferilee/api-niyyah2:latest
    container_name: api-niyyah2
    restart: unless-stopped
    ports:
      - "3003:3000" # Mapping port luar 3003 ke port dalam container 3000
    env_file:
      - .env
    networks:
      - ferileeNet

networks:
  ferileeNet:
    external: true
